### ISSUE TITLE
grafanaplugin disable query button doesn't work

### ISSUE THREAD

**Issue by t00350320** [taosdata/grafanaplugin#34]
grafana version:grafana-8.0.4-1.x86_64.rpm
grafanaplugin from: TDengine-server-2.1.3.2-Linux-x64.tar.gz

when disable a query sql, the result also refresh at current panel.

**Comment by afwerar** [comment]
This problem will be fixed in the new version in a few days.

**Comment by afwerar** [comment]
Now you can try the new version 3.0.0, this problem has been solved.

**Comment by zitsen** [comment]
Closed since there's no discussions in 30 days. reopen it as free if not fixed.
